spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/template/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
file-path:
  server: /Users/gimtaeyeon/fileTest/servers.json
  user: /Users/gimtaeyeon/fileTest/user/{username}